### PR TITLE
Delete app_zh_Hans.arb

### PR DESCRIPTION
**Pull request by wuhang2003**
Prevent conflicts in Weblate

### CODE REVIEW

**Comment by Craftplacer** [comment]
Were the translations applied from zh_Hans to zh? Just trying to make sure we aren't deleting anything destructively.

**Comment by wuhang2003** [comment]
@Craftplacer With Poesty Li help, all translations in zh have been completed. So it can be deleted safely.

**Comment by wuhang2003** [comment]
@Craftplacer Another question, When will the new translation be applied? New Weekly released?

**Comment by Craftplacer** [comment]
Theorectically after the first commit on the main repository after this pull request. Publicly released after this week, yes.

**Pull request merged**
