### PR TITLE
Update app_en.arb

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
https://github.com/Kaiteki-Fedi/Kaiteki/pull/213

### CODE REVIEW

**Comment by Craftplacer** [comment]
Your translation key does not match up with the linked PR...

**Comment by ThatOneCalculator** [comment]
it dont matter anymore :3

**Comment by ThatOneCalculator** [comment]
oh nvm it does

**Comment by ThatOneCalculator** [comment]
@Craftplacer

**Pull request merged**
